package org.jetbrains.kotlinx.ggdsl.echarts.translator.option

import kotlinx.serialization.Serializable
import org.jetbrains.kotlinx.ggdsl.echarts.translator.option.series.Series

@Serializable
public data class Option(
    val title: Title? = null,
    val legend: Legend? = null,
    val grid: Grid? = null,
    val xAxis: Axis? = null,
    val yAxis: Axis? = null,
    val polar: Polar? = null,
    val radiusAxis: RadiusAxis? = null,
    val angleAxis: AngleAxis? = null,
    val radar: Radar? = null,
//    val dataZoom: List<DataZoom>,
//    val visualMap: List<VisualMap>,
//    val tooltip: Tooltip,
//    val axisPointer: AxisPointer,
//    val toolbox: Toolbox,
//    val brush: Brush,
//    val geo: Geo,
//    val parallel: Parallel,
//    val parallelAxis: ParallelAxis,
//    val timeline: Timeline,
//    val graphic: Graphic,
//    val calendar: Calendar,
    val dataset: Dataset? = null,
//    val aria: Aria,
    val series: List<Series>? = null,
//    val darkMode: Boolean,
//    val color: Color,
//    val backgroundColor: Color,
//    val textStyle: TextStyle,
//    val animation: Boolean,
//    val animationThreshold: Int,
//    val animationDuration: Int,
//    val animationEasing: String,
//    val animationDelay: Int,
//    val animationDurationUpdate: Int,
//    val animationEasingUpdate: String,
//    val animationDelayUpdate: 0,
//    val stateAnimation: StateAnimation,
//    val blendMode: String,
//    val hoverLayerThreshold: Int,
//    val useUtc: Boolean,
//    val options: List<ECUnitOption>,
//    val media: List<Media>
)